package com.devglan.dao;


import com.devglan.model.user.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.Assert;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.boot.test.context.SpringBootTest;


@RunWith(SpringRunner.class)
@SpringBootTest
public class UserDaoTest {

    // Mouna => https://mkyong.com/tutorials/junit-tutorials/

    @Autowired
    UserDao userDaoRepository;


    @BeforeClass
    public static void runOnceBeforeClass() {
        System.out.println("@BeforeClass - runOnceBeforeClass");
    }

    @AfterClass
    public static void runOnceAfterClass() {
        System.out.println("@AfterClass - runOnceAfterClass");
    }

    @Test
    public void testRepository() {
        User user = new User();
        // user.setId(); => AutoGeneratedValue
        user.setFirstName("Devglan");
        user.setLastName("Devglan");
        user.setEmail("devglan@gmail.com");
        user.setPassword("devglan");
        user.setTypeUser("R");

        userDaoRepository.save(user);
        Assert.assertNotNull(user.getId());
        System.out.println("Test userDaoRepository: "+ user.getId());
    }
}
